version: "3.8"

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: lorenzodev
      POSTGRES_PASSWORD: lorenzodev12345
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://lorenzodev:lorenzodev12345@localhost:5432/schooldb
    depends_on:
      - postgres
